### ISSUE TITLE
[FEATURE] SDK support for oAuth2 authentication for ZIA

### ISSUE THREAD

**Issue by gopurx** [zscaler/zscaler-sdk-python#155]
**Problem Statement**
Not able to use SDK when Zscaler is enabled for oAuth2 

**Proposed Solution**
Supporting SDK for oAuth2 authentication

**Additional Context**
Add any other context, references or screenshots about the feature request here.

**Comment by willguibr** [comment]
@gopurx 
I assume you're referring to Zscaler's Zslogin for OneAPI?
Can you provide further insight on it?
Thanks
Zscaler DevRel

**Comment by gopurx** [comment]
Planning to use Zscaler SDK for managing location and static IP addresses ZIA, checking if this SDK support oAuth2 as authentication while accessing API. If yes, can you please point to documentation on how to pass related parameters

**Comment by willguibr** [comment]
The SDK currently only supports the static authentication method offered by the ZIA API as described in the README [here](https://github.com/zscaler/zscaler-sdk-python?tab=readme-ov-file#authentication)
Oauth2, will be supported in the future  via the OneAPI platform. For more information on OneAPI please refer to the documentation [here](https://help.zscaler.com/oneapi) or contact your local account team for more details and timelines.

Regards,
Zscaler DevRel
