### ISSUE TITLE
[FEATURE] how to add static location group while creating/updating a location

### ISSUE THREAD

**Issue by gopurx** [zscaler/zscaler-sdk-python#172]
**Problem Statement**
Did not found an option to add/manage static location group while adding a location. Did not even found on API as well, is this feature exposed over API?

**Proposed Solution**

**Additional Context**
Add any other context, references or screenshots about the feature request here.

**Comment by willguibr** [comment]
@gopurx Adding actual location groups is not currently available via public APIs for POST/PUT/DELETE calls. Only GET method is currently exposed.
When configuring a location management you can associate a static location by setting the attribute list `static_location_groups`. See the example below:
```py
response = created_location = zia.locations.add_location(
            name='Location_Management01',
            tz="UNITED_STATES_AMERICA_LOS_ANGELES",
            profile='CORPORATE',
            auth_required=True,
            idle_time_in_minutes=720,
            display_time_unit="HOUR",
            surrogate_ip=True,
            xff_forward_enabled=True,
            ofw_enabled=True,
            ips_control=True,
            vpn_credentials=[{"id": 115493444, "type": "UFQDN"}],
            static_location_groups=[{"id": 64365143}],
```

The attribute is unfortunately not documented in our public swagger, so we'll submit a request to our documentation team to rectify that.

**Comment by willguibr** [comment]
Closing as there's been no updates.

Zscaler DevRel
