### ISSUE TITLE
method locations.get_location_group_by_name() does not filter by name

### ISSUE THREAD

**Issue by gopurx** [zscaler/zscaler-sdk-python#175]
method locations.get_location_group_by_name() returns all groups, does not filter by name. Suspecting the param for search should be name vs group name.

https://github.com/zscaler/zscaler-sdk-python/blob/432e1a1ff8bce3055b022de524c35ae00c0c21cf/zscaler/zia/locations.py#L536

**Comment by willguibr** [comment]
@gopurx 
We have actually been deprecated the `get_location_group_by_name `  on version v0.9.5. Please use the method `list_location_groups` instead which takes several parameters i.e `name`. 

Zscaler DevRel
