### ISSUE TITLE
[ISSUE] Cannot push complex conditions with AND/OR operator

### ISSUE THREAD

**Issue by martinkiska** [zscaler/zscaler-sdk-python#198]
**Description**
After latest changes in in 0.9.6 in _create_conditions_v1 part (https://github.com/zscaler/zscaler-sdk-python/blob/668f1e5c25fa84e2979238d4f05b25bf1317f2a7/zscaler/zpa/policies.py#L164C46-L164C62) is used latest operator from all passed conditions, thus it is not following expected AND/OR values for other conditions.

**Reproduction**
```
fixed_rule = {
    "id": "288262342519555397",
    "app_connector_groups": [],
    "app_server_groups": [],
    "conditions": [
        # ("OR", ("CLIENT_TYPE", "id", "zpn_client_type_exporter")),
        # ("OR", ("CLIENT_TYPE", "id", "zpn_client_type_browser_isolation")),
        # ("OR", ("CLIENT_TYPE", "id", "zpn_client_type_browser_isolation")),
        ("OR",("PLATFORM","ios","True",),),
        ("OR",("PLATFORM","android","True",),),
        ("AND",("POSTURE", "cfa7d843-62cc-479f-aac6-d07a0798f0be", "True"),),
        ("AND", ("POSTURE", "06d14aab-75d7-498a-9d03-1ae679da4fa9", "True")),
    ],
}

zpa.policies.update_access_rule(
    rule_id=fixed_rule.pop("id"),
    **fixed_rule,
)
```

**Expected behavior**

Have PLATFORM configured with OR operator and POSTURE with AND

**Is it a regression?**

I think that AND operator was not processed by previous versions in any conditions. So it was somehow implemented in 0.9.6, but wrongly implemented.

**Debug Logs**

```
User-Agent: zscaler-sdk-python/0.9.6 python/3.10.9 Linux/5.15.153.1-microsoft-standard-WSL2

{"id": "288262342519555397", "modifiedTime": "1730453456", "creationTime": "1711458922", "modifiedBy": "288262342519554083", "name": "my_name", "description": "MyDescription", "ruleOrder": "2", "priority": "64", "policyType": "1", "operator": "AND", "conditions": [{"operator": "OR", "operands": [{"objectType": "PLATFORM", "lhs": "ios", "rhs": "True"}, {"objectType": "PLATFORM", "lhs": "android", "rhs": "True"}]}, {"operator": "OR", "operands": [{"objectType": "POSTURE", "lhs": "cfa7d843-62cc-479f-aac6-d07a0798f0be", "rhs": "True"}, {"objectType": "POSTURE", "lhs": "06d14aab-75d7-498a-9d03-1ae679da4fa9", "rhs": "True"}]}], "action": "ALLOW", "disabled": "0", "extranetEnabled": false, "policySetId": "288262342519554053", "defaultRule": false, "appConnectorGroups": [], "appServerGroups": [], "appConnectorGroupIds": [], "appServerGroupIds": []}
```

**Additional context**
This was implemented in Mitchos SDK via this PR https://github.com/mitchos/pyZscaler/issues/146

**Comment by willguibr** [comment]
@martinkiska This is a duplicated case and is being already investigated via an internal Zscaler support case you've raised. We will provide an answer and potential fix via that support case on a timely fashion.

Zscaler DevRel.

**Comment by willguibr** [comment]
@martinkiska we're reopening this case as an exception here.
Can you please take a look at the following branch [zpa-#199-fix/fixed-complex-condition-template](https://github.com/zscaler/zscaler-sdk-python/tree/zpa-%23199-fix/fixed-complex-condition-template) and test the configuration you're proposing?
For objectTypes such as PLATFORM, COUNTRY_CODE and a few others, the operator is implicit and not visible in the actual UI. In other words, it's only configurable via APII.
Either way, our tests with the new fix show it's working now. Please test and let us know if it suffices what you're looking for.

Regards,

Zscaler DevRel

**Comment by willguibr** [comment]
@martinkiska For policies at this time we won't be implementing the suggested logic, as there are other implications we have to take into consideration. We are in the process of performing some modifications in the underlying framework due to OneAPI and other requirements. As per the original request, I assume we have already addressed the issue reported, so we ask you to please test and let us know if that works for you, so that we can publish a new minor release.
Thank you

Zscaler DevRel
