### ISSUE TITLE
[FEATURE] PAC Files manipulation (get, post)

### ISSUE THREAD

**Issue by ActualReverend** [zscaler/zscaler-sdk-python#201]
**Problem Statement**
PAC file manipulation has ben released in the official API, but this library doesn't appear to have.  https://help.zscaler.com/zia/pac-files#

**Proposed Solution**
ZIA portion of this library be updated to include adding, getting, removing PAC files, leveraging the new API functionality.

I looked in https://github.com/zscaler/zscaler-sdk-python/tree/master/zscaler/zia , but didn't see anything that looked like PAC file manipulation, so my apologies if I missed it somewhere else.

**Comment by willguibr** [comment]
@ActualReverend This is a newly released API (4 days ago) only available in specific clouds at the moment.
We will evaluate the feasibility of including the new endpoints in upcoming releases.

Zscaler DevRel
