### ISSUE TITLE
[ISSUE] Unable to push SCIM and SCIM_GROUP conditions together with OR logic

### ISSUE THREAD

**Issue by martinkiska** [zscaler/zscaler-sdk-python#214]
**Description**
Unable to create rule with SCIM and SCIM_GROUP condition together via API. 

Normally via GUI it is created in a way, that it follows OR logic, what make sense. When I click it via web, I can see that access policy works for AD group or user.

![image](https://github.com/user-attachments/assets/3026b300-a4b6-47c7-95bc-c38d95015b51)

If I want to send it via API, SDK allows me kwargs of conditions and afterwards it is grouped. So I send this list of conditions to _create_condition_v1 function:

![image](https://github.com/user-attachments/assets/3bcbec8f-ec12-444e-810a-484dea5aeb43)

On [L130](https://github.com/zscaler/zscaler-sdk-python/blob/b4f340a107d3885d1befd3e6b78e55ea719fb180/zscaler/zpa/policies.py#L130) SDK correctly parses APP and APP_GROUP into one block. But this logic is missing for SCIM/SCIM_GROUP, due to that SCIM and SCIM_GROUP are taken as separate conditions with AND logic what doesn't make sense.
![image](https://github.com/user-attachments/assets/7cdabdc9-ef71-45ed-9fdb-baddc0cbd740)

This can be also visible in UI after rest.put. Where UI is unable to show it in view mode, but in edit mode of the rule you can see that there is AND logic, what doesn't make sense and you are unable to create such rule via UI.

![image](https://github.com/user-attachments/assets/20550d4e-6e1b-477f-91ce-367b66c4d0fb)

**Reproduction**
Shared in prtscrs. Just push whatever rule with SCIM and SCIM_GROUP conditions.

**Expected behavior**
See it in UI with OR logic

**Is it a regression?**
I don't think it was ever working. Just started migration to official SDK and I am facing issues during onboarding. It was tested on 0.9.7

**Debug Logs**
The SDK logs are helpful in debugging information when debug logging is enabled. Set the log level to debug by adding `logging.basicConfig(level=logging.DEBUG)` to your program, and include the logs here. You can also set the following environment variables in order to enable logging:
* `ZSCALER_SDK_LOG` - Turn on logging
* `ZSCALER_SDK_VERBOSE` - Turn on logging in verbose mode

**Other Information**
 - OS: [e.g. macOS]
 - Version: [e.g. 0.1.0]

**Additional context**

**Comment by martinkiska** [comment]
Thanks @willguibr to drive this further. I created an ISSUE, last time when I wrote some lines with fix they were not accepted so I didn't propose anything. As there was no response for more than week I created support ticket pointing to this ISSUE. Support responded in a way that they are able to push it via Postman. So in the reply I wanted to make it quicker and proposed them the PR so they know whom to ask exactly...

Hopefully SDK will be now ready for full migration of our ZPA policies/apps/.... automation.

**Comment by willguibr** [comment]
@martinkiska Please test your configuration against the latest version pushed in the [branch](https://github.com/zscaler/zscaler-sdk-python/tree/zpa-%23225-fix-policy-conditions-template)
Once you confirm, we'll publish a new release.

Zscaler DevRel

**Comment by martinkiska** [comment]
Hi @willguibr,
I was able to verify it with this [branch](https://github.com/zscaler/zscaler-sdk-python/tree/zpa-%23225-fix-policy-conditions-template). I am able to push policies with expected OR operator with SCIM/SCIM_GROUP conditions!

Thank you!

**Comment by willguibr** [comment]
The issue has been resolved via the new minor release 0.10.1

Zscaler DevRel
